### ISSUE TITLE
✨ [Feature] main page 더미 데이터 요청

### ISSUE THREAD

**Issue by Hawardshin** [42masterplan/ft_transcendence-back#45]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 메인 페이지 동작을 위해서 더미데이터를 요청합니다.

## 📝 기능 상세 내용

[ Get users/info/{id} ]
```
{
  id: '1',
  name: 'Seoyoo',
  profileImage: 'http://localhost:8080/resources/crocodile_health.svg',
  currentStatus: 'on-line',
  introduction:
    'Hello, I am User1 and this is a very very very very long long long long long long introduction. ',
  rank: {
    win: 10,
    lose: 5,
    tier: 'Silver'
  },
  challenges: [
    {
      name: 'Challenge1',
      description: 'This is challenge1',
      progressRate: 25,
      achieveRatio: 0.5
    },
    {
      name: 'Challenge2',
      description: 'This is challenge2',
      progressRate: 0,
      achieveRatio: 0.5
    },
    {
      name: 'Challenge3',
      description: 'This is challenge3',
      progressRate: 14,
      achieveRatio: 1
    },
    {
      name: 'Challenge4',
      description: 'This is challenge4',
      progressRate: 23,
      achieveRatio: 1
    },
    {
      name: 'Challenge5',
      description: 'This is challenge5',
      progressRate: 33,
      achieveRatio: 1
    },
    {
      name: 'Challenge6',
      description: 'This is challenge6',
      progressRate: 44,
      achieveRatio: 1
    },
    {
      name: 'Challenge7',
      description: 'This is challenge7',
      progressRate: 55,
      achieveRatio: 1
    },
    {
      name: 'Challenge8',
      description: 'This is challenge8',
      progressRate: 66,
      achieveRatio: 1
    },
    {
      name: 'Challenge9',
      description: 'This is challenge9',
      progressRate: 77,
      achieveRatio: 1
    },
    {
      name: 'Challenge10',
      description: 'This is challenge10',
      progressRate: 100,
      achieveRatio: 1
    },
    {
      name: 'Challenge11',
      description: 'This is challenge11',
      progressRate: 100,
      achieveRatio: 1
    },
    {
      name: 'Challenge12',
      description: 'This is challenge12',
      progressRate: 100,
      achieveRatio: 1
    },
    {
      name: 'Challenge13',
      description: 'This is challenge13',
      progressRate: 100,
      achieveRatio: 1
    },
    {
      name: 'Challenge14',
      description: 'This is challenge14',
      progressRate: 100,
      achieveRatio: 1
    },
    {
      name: 'Challenge15',
      description: 'This is challenge15',
      progressRate: 100,
      achieveRatio: 1
    },
    {
      name: 'Challenge16',
      description: 'This is challenge16',
      progressRate: 100,
      achieveRatio: 1
    },
    {
      name: 'Challenge17',
      description: 'This is challenge17',
      progressRate: 100,
      achieveRatio: 1
    },
    {
      name: 'Challenge18',
      description: 'This is challenge18',
      progressRate: 100,
      achieveRatio: 1
    },
    {
      name: 'Challenge19',
      description: 'This is challenge19',
      progressRate: 100,
      achieveRatio: 1
    }
  ]
};
```

Get users/game-history/{id}
```
[
  {
    createdAt: '2021-05-01',
    player1Name: 'User1',
    player2Name: 'User2',
    player1Score: 0,
    player2Score: 0
  },
  {
    createdAt: '2021-05-02',
    player1Name: 'User1',
    player2Name: 'User3',
    player1Score: 5,
    player2Score: 10
  },
  {
    createdAt: '2021-05-03',
    player1Name: 'User1',
    player2Name: 'User4',
    player1Score: 10,
    player2Score: 5
  },
  {
    createdAt: '2021-05-04',
    player1Name: 'User1',
    player2Name: 'User5',
    player1Score: 5,
    player2Score: 10
  },
  {
    createdAt: '2021-05-05',
    player1Name: 'User1',
    player2Name: 'User6',
    player1Score: 10,
    player2Score: 5
  },
  {
    createdAt: '2021-05-06',
    player1Name: 'User1',
    player2Name: 'User7',
    player1Score: 5,
    player2Score: 10
  },
  {
    createdAt: '2021-05-07',
    player1Name: 'User1',
    player2Name: 'User8',
    player1Score: 10,
    player2Score: 5
  },
  {
    createdAt: '2021-05-08',
    player1Name: 'User1',
    player2Name: 'User9',
    player1Score: 5,
    player2Score: 10
  },
  {
    createdAt: '2021-05-09',
    player1Name: 'User1',
    player2Name: 'User10',
    player1Score: 10,
    player2Score: 5
  },
  {
    createdAt: '2021-05-10',
    player1Name: 'User1',
    player2Name: 'User11',
    player1Score: 5,
    player2Score: 10
  },
  {
    createdAt: '2021-05-11',
    player1Name: 'User1',
    player2Name: 'User12',
    player1Score: 10,
    player2Score: 5
  },
  {
    createdAt: '2021-05-12',
    player1Name: 'User1',
    player2Name: 'User13',
    player1Score: 5,
    player2Score: 10
  },
  {
    createdAt: '2021-05-13',
    player1Name: 'User1',
    player2Name: 'User14',
    player1Score: 10,
    player2Score: 5
  },
  {
    createdAt: '2021-05-14',
    player1Name: 'User1',
    player2Name: 'User15',
    player1Score: 5,
    player2Score: 10
  },
  {
    createdAt: '2021-05-15',
    player1Name: 'User1',
    player2Name: 'User16',
    player1Score: 10,
    player2Score: 5
  },
  {
    createdAt: '2021-05-16',
    player1Name: 'User1',
    player2Name: 'User17',
    player1Score: 5,
    player2Score: 10
  },
  {
    createdAt: '2021-05-17',
    player1Name: 'User1',
    player2Name: 'User18',
    player1Score: 10,
    player2Score: 5
  },
  {
    createdAt: '2021-05-18',
    player1Name: 'User1',
    player2Name: 'User19',
    player1Score: 5,
    player2Score: 10
  },
  {
    createdAt: '2021-05-19',
    player1Name: 'User1',
    player2Name: 'User20',
    player1Score: 10,
    player2Score: 5
  }
];
```
## ✅ TODO

- [x] 일단 더미 API 먼저 만들어주세요
- [ ] 이게 생성되면, 업적도 DB 올리는 거 해주시면 될듯..! 화이팅!
